#This playbook sets up the beaker server and lab controller
---
# https://fedoramagazine.org/getting-ansible-working-fedora-23/
- hosts: localhost
  become_user: root
  become: yes
  gather_facts: false
  tasks:
    - name: are we running on Fedora?
      raw: python -c "import platform; import sys; sys.stdout.write(platform.linux_distribution(full_distribution_name=False)[0])"
      register: host_distro
    - name: ensure python and deps for ansible modules are installed
      raw: dnf install -y python2 python2-dnf libselinux-python
      when: host_distro.stdout.find('fedora') != -1
      # only run this on fedora hosts, RHEL doesn't have this problem

- hosts: localhost
  become: true

  vars:
    user_key_path_default: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    user_key: "{{ lookup('file', '{{ user_key_path }}') }}"
    storage_pool_name_default: "default"
    storage_min_size: 42949672960
    netinstall_url: http://mirror.centos.org/centos/6/os/x86_64
    kickstart_repos:
      install: http://mirror.centos.org/centos/6/os/x86_64/
      updates: http://mirror.centos.org/centos/6/updates/x86_64/
      extras: http://mirror.centos.org/centos/6/extras/x86_64/
      cr: http://mirror.centos.org/centos/6/cr/x86_64/
    user_distros: []

  vars_prompt:
    - name: "user_key_path"
      prompt: "What is the absolute path to the public ssh key you wish
              to use (note: the path cannot include '~')? If you don't
              have one at all one can be generated with
              'mkdir -p ~/.ssh && ssh-keygen'"
      private: no
      default: "{{ user_key_path_default }}"
    - name: "storage_pool_name"
      prompt: "What libvirt storage pool would you like to use?"
      private: no
      default: "{{ storage_pool_name_default }}"

  roles:
    - { role: local, tags: [local] }
    - { role: libvirt, tags: [network] }
    - { role: serverlc, tags: [serverlc] }
    - { role: test-systems, tags: [systems] }

- hosts: serverlc
  remote_user: root
  roles:
    - { role: beaker/common, tags: [serverlc, common] }
    - { role: beaker/setup/repos, tags: [serverlc, repos] }
    - { role: beaker/setup/database, tags: [serverlc, database] }
    - { role: beaker/setup/services, tags: [serverlc, services] }
    - { role: beaker/data/labcontroller, tags: [serverlc, labcontroller, data] }
    - { role: beaker/data/testsystems, tags: [serverlc, systems, data] }
    - { role: beaker/data/distros, tags: [serverlc, distros, data] }
    - { role: beaker/data/beakertasks, tags: [serverlc, tasks, data] }
