---
- name: ensure libvirt is installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-daemon-kvm
    - virt-manager
    - libvirt-client

- name: ensure libvirt and virtlogd are enabled/started
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - libvirtd
    - virtlogd

- name: define and start beaker networks
  virt_net:
    command: define
    name: "{{ network.name }}"
    xml: "{{ lookup('template', 'config.xml.j2') }}"

- name: activate beaker networks
  virt_net:
    state: active
    name: "{{ network.name }}"

- name: "does libvirt pool '{{storage_pool_name}}' have >= 40G of total space"
  virt_pool:
    command: facts
  failed_when: ansible_libvirt_pools[storage_pool_name].size_total | version_compare(storage_min_size, '<')

- name: ensure user provided storage pool is active
  virt_pool:
    state: active
    name: "{{ storage_pool_name }}"
    autostart: yes
